< DOCTYPE:HTML> 


<head>

<meta charset UTF-8">

<title>Kassia Rafaella</title>

<style>

h1 {

color: rgb(25, 26, 24); text-align: center;

}

color: rgb(137, 252, 92);

text-align: center;

</style>

</head>

<body>

<H1> O MAIOR CAMPEÃO DO BRASIL!</H1>

<p> 0 <b> Palmeiras</b> segue a 7 passos de conquistar seu 11° <strong> Título Brasileiro! </strong></p>


</body>



</html>
